### ISSUE TITLE
V2 Todo

### ISSUE THREAD

**Issue by jorgebucaran** [hyperapp/hyperapp#696]
As most of you may be well aware of, Hyperapp 2.0 is coming #672. 🎉 

Here's my todo list before I am ready to publish its beta test version.

---

- [x] Split up code base into one file per every function (`clone.js`, `patch.js`, `h.js`, `app.js`, etc.)
- [x] Optimize `defer` function. Instead of `setTimeout`, use Promise.resolve (faster).
- [x] Implement new internals `dispatch`, `setState`, `runCommand`, `render`.
- [x] Update DOM manipulation functions (`patch`, `createElement`, `updateAttribute`) to accept `resolveNode` and `eventProxy`).
  - [x] Implement new `resolveNode` to support `children` as a prop.
  - [ ] Determine how the new lazy components (dynamic) components will be implemented, e.g., passing `dispatch` as the second argument to every component or similar.
- [x] Implement the Subscriptions API.
  - ~~[ ] Publish an independent library that demonstrates (or expands on) these ideas to start a discussion.~~
- ~~[ ] Implement targeted merges.~~
- [x] Add support to `updateAttribute` to compute a `Element.className` from an object, similar to [classcat](https://github.com/JorgeBucaran/classcat), but built-in.
- [ ] Fix and add new tests.
- [ ] Decide how the middleware API should work. /cc @okwolf 

Your comments and feedback, please! 🙏

**Comment by selfup** [comment]
Glad there is a thought out plan! Looking forward to the changes 🙏

**Comment by Swizz** [comment]
The topic we were all awaiting 🎉

Is there some things we can help on ?

**Comment by jorgebucaran** [comment]
@Swizz Tests 😅and testing the beta release when it's published, also documentation ideas and the website, but notice I didn't include that on the todo list. Hyperapp 2.0 is coming first.

**Comment by Swizz** [comment]
With a grateful 1.x to 2.x path, the adoption will be easier.

Hyperapp 1.x is not here since years, and I am pretty sure, Hyperapp 2.x will allow all this features to live in userland :+1:

**Comment by SkaterDad** [comment]
> @jorgebucaran  3.1. There may be lazy components, after all, I'm not too sure about it. How are you using its context-like functionality? I'd really like to hear that.

My main app codebase was mostly in place by the time lazy components landed, so I'm not using them very much yet.  There's one or two places where I used them to access state, but those components weren't deeply nested, so I mostly did it because I could.   I'm sure some other people have used/abused it more than I have :laughing: 

The biggest benefit my app had from lazy components was being able to access the global actions object, especially for my router's `Link` component.  With 2.0's version of actions, this use case goes away.

**Comment by infinnie** [comment]
Yeah access to global state and actions are somewhat like the new context API in React. But maybe it not only allows for dynamic actions without rewriting the actions, but could provide us with a more elegant alternative to things like Redux as well.

**Comment by infinnie** [comment]
And we want to see it public ASAP.

**Comment by infinnie** [comment]
And maybe we could write components like

```jsx
// This is only possible because Connector is a lazy component
// that knows the underlying state
// Or maybe mutations should know the state whole?
var Component = function (props) {
    return (<Connector render={function (stateSlice, mutations, operations) {
        return (<Selector from={stateSlice} render={function (selectedState) {
            // Actual rendering goes here.
        }} />);
    }} />);
};
```

In the React community, there has been a recommended practice that
> In general, the shape of the state is something only reducers should know about. The moment it leaks out of the store, code becomes structurally coupled.

> Since reducers decide what’s the shape because they write it. It’s just common sense to make the “read” happen close to them with selectors.

> As a rule of thumb, doing `state.` is a mistake. The only place where that should be allowed is inside a selector. But only as long as the selector is [collocated] in the reducer which is responsible for that part of the state.
—https://hackernoon.com/selectors-in-redux-are-a-must-d6b0637c79b7

**Comment by infinnie** [comment]
@jorgebucaran thanks. 🐈

**Comment by ThobyV** [comment]
I'm so excited about this, I can't wait to start beta testing. I'd love to **render** some though. 😎

**Comment by bardiarastin** [comment]
Hi, is there any reason code is not written in ES6 ?

**Comment by jorgebucaran** [comment]
@bardiarastin Other than ES modules, we're not using any modern JavaScript idioms.

The main reason is I want full control over the code I am writing and shipping and don't want to introduce a build step to the project. It's a modest attempt to make a case for simplicity.

**Comment by okwolf** [comment]
👍  for a new subscription library

👍  for middleware API

**Comment by jorgebucaran** [comment]
#703

**Comment by dcustodio** [comment]
First of all thanks for Hyperapp 1.x, it was just what I needed and all in a tiny lib. 
I have a couple of projects running in 1.x that are good candidates to beta test the 2.0.

**Comment by rbiggs** [comment]
Curious if you'll refactor patch algo to improve Hyperapp performance in comparison to other frameworks on Stefan Krause's js-framework-benchmark.

**Comment by jorgebucaran** [comment]
@rbiggs Not for 2.0, but after (when I have time again). FWIW #663 improved those numbers substantially. You are welcome to discuss performance more in #499.

**Comment by jorgebucaran** [comment]
@emil14 Hyperapp doesn't need any modern JavaScript features at the moment, so performance is not affected because of this decision. For example, if we wanted to use Set or Map and because of poor browser support shipped our own shims, then you'd be totally right  — we'd be better off using the browser's native Set and Map. 

Things Hyperapp doesn't use or avoids without affecting its perf: 

- Classes, `this`, prototypes
- Set, Map, WeakSet, WeakMap
- Block-Scoped (let, const)
- Destructuring

**Comment by leeoniya** [comment]
FWIW, not using prototypes may in fact negatively affect performance. But you don't need any modern JS features or tooling to use them if you wanted to.

**Comment by jorgebucaran** [comment]
@leeoniya's 

I am not saying I could've used prototypes, but decided not to because I have thisphobia. 😄  

I am saying Hyperapp doesn't make use of prototypes. Hyperapps don't have methods or properties and there are no app instances either. In 1.0, even if you had multiple apps running on the same page (not encouraged either) they are unlikely to share the same implementation of actions, so you'd need to create a different actions object for each app call.

In 2.0 there is _not even_ an actions object, so I've yet to find a use case for prototypes in Hyperapp.

**Comment by leeoniya** [comment]
i also keep `this` and `new` out of domvm's public apis. however, there are legitimate perf reasons for using prototypes internally.

**Comment by jorgebucaran** [comment]
Thanks, if you find a good reason to use it in Hyperapp let us know.

**Comment by emil14** [comment]
@jorgebucaran 

Thank you for your answer! But I still don't agree with you :)

You can write sources in ESNext and let us to choose, should we transpile it or not, what browser support we need. You can ship ES5 via CDN and add something like `hyperapp.es5.js` to the npm-package, don't you?

If you afraid of greater bundle size, generated by `Webpack/Parcel/Rollup` - do you really think it's so important ? :)

> Classes, this, prototypes

I can understand that. These features are not very "functional", but the rest of them are good

**Comment by dmitrykurmanov** [comment]
Do we have first implementation of readme or some examples for the hyperapp v2.0 ?

**Comment by infinnie** [comment]
A few ES 6 features could have been useful like promises 😉

**Comment by okwolf** [comment]
I believe subscriptions are already implemented, but are you still planning to include `classcat` style support?

**Comment by jorgebucaran** [comment]
@okwolf Yes, I want to. What do you think? :)

**Comment by okwolf** [comment]
@jorgebucaran I like the idea. How much bloat are we talking about adding?

**Comment by frenzzy** [comment]
Please no, it is not needed in case of using `CSS Modules` or `CSS in JS`.

**Comment by jorgebucaran** [comment]
@okwolf Not a lot. See https://github.com/jorgebucaran/classcat

@frenzzy This feature is consistent and harmonious with VDOM, but you make a point. How do you personally use CSS modules or CSS in JS with Hyperapp? Do you have any examples? Maybe that could help me decide.

**Comment by zaceno** [comment]
@frenzzy I don't understand. How does CSS modules or CSS in JS make classcat unnecessary?

With plain css I'd use it like this:

```
<ul>
  {items.map((text, index) => (
    <li class={cc({
      highlight: index === state.selected,
      disabled: state.disabled.indexOf(index) >= 0
    })}> {text} </li>
  )}
</ul>
```

with css moduled (with classes imported as the var `style`), like this:

```
<ul>
  {items.map((text, index) => (
    <li class={cc({
      [style.highlight]: index === state.selected,
      [style.disabled]: state.disabled.indexOf(index) >= 0
    })}> {text} </li>
  )}
</ul>
```

sure, the syntax is a little more verbose with css modules, but in both cases `classcat` (`cc` in the example) significantly simplifies the code for toggling and concatenating classes. And that's quite a common need. In fact I use it in all but my most trivial projects. So I'm pro including it.

**Comment by dmitrykurmanov** [comment]
May be `classcat` (and probably other features) can be separate module because of flexibility? Everyone can include it if wants or not. Also I think that it can be exists in the official doc as the recommended way.

**Comment by zaceno** [comment]
I think it's mostly a question of: how will this feature behave when you *don't* need to toggle classes. I think these should (and would) all work as expected with cc included:

`class={'foo'}`
`class={'foo bar'}`
`class={['foo', 'bar']}`
`class={{foo: isFoo()}`
`class={['foo', {bar: isBar()}]}`

**Comment by jorgebucaran** [comment]
@zaceno Yep, as you said, they'd all work.

**Comment by thibautRe** [comment]
> How do you personally use CSS modules or CSS in JS with Hyperapp?

The way I use it right now is like this

``` js
// This helper generates a className and insert a style rule in the DOM.
// I can be for instance emotion-js, CSS modules "import", or a custom helper
const componentClass = generateClass('/* CSS rules here */')

const MyComponent = (props) => (
  <div class={componentClass} />
)
```

With conditional styles, I usually use ES6 string interpolation:

``` js
// This helper generates a className and insert a style rule in the DOM.
// I can be for instance emotion-js, CSS modules "import", or a custom helper
const componentBase = generateClass('/* CSS rules here */')
const isComponentActive = generateClass('')
const themes = {
  RED: generateClass('/* red theme */'),
  BLUE: generateClass('/* blue theme */'),
}

const MyComponent = ({ active, theme }) => (
  <div
    class={`
      ${componentBase}
      ${active && isComponentActive}
      ${themes[theme || 'RED']}
    `}
  />
)

// By default: inactive, default theme is red
<MyComponent />

// Activates the blue theme
<MyComponent active theme="BLUE" />
```

For my use cases, a classcat helper is not necessary.

**Comment by gpoitch** [comment]
Usually use this simple inline class concat or can extract to a helper if used a lot:

```js
import style from './style.css'

const FooComponent = ({ active }) => (
  <div class={[style.foo, active && style.active].filter(Boolean).join(' ')} />
)
```

**Comment by jorgebucaran** [comment]
@thibautRe @gpoitch Thanks for sharing that.

Well, it seems neither CSS modules or CSS in JS would interfere with a classcat-like built-in functionality.

**Comment by SkaterDad** [comment]
Having classcat-like functionality built-in would be handy sometimes.

I pretty much exclusively use [Tailwind.css](https://tailwindcss.com/docs/what-is-tailwind/) now, with some sprinkles of custom CSS classes, so the CSS-in-JS stuff is a non-issue.

**Comment by mrozbarry** [comment]
@jorgebucaran did we drop the idea of middleware? If not, maybe classcat could be vdom middleware that checks props for class, and if it's an object, parses, and if it's a string, passes that through as normal - that keeps it out of everyone's hair, but would make it easy enough to flip a switch and enable it.

**Comment by jorgebucaran** [comment]
> @mrozbarry did we drop the idea of middleware?

Not quite! See #703.

**Comment by jorgebucaran** [comment]
Closing for #726.
